
import { TestConfig, QuestionOption } from '../../types/assessment';

const SCALE_OCEAN: QuestionOption[] = [
  // Corrected German translation 'não zu' -> 'nicht zu'
  { label: { pt: 'Discordo Totalmente', en: 'Strongly Disagree', es: 'Totalmente en desacuerdo', fr: 'Fortement en Désaccord', de: 'Stimme überhaupt nicht zu' }, value: 1 },
  { label: { pt: 'Discordo', en: 'Disagree', es: 'En desacuerdo', fr: 'En Désaccord', de: 'Stimme nicht zu' }, value: 2 },
  { label: { pt: 'Neutro', en: 'Neutral', es: 'Neutral', fr: 'Neutre', de: 'Neutral' }, value: 3 },
  { label: { pt: 'Concordo', en: 'Agree', es: 'De acordo', fr: 'D\'accord', de: 'Stimme zu' }, value: 4 },
  { label: { pt: 'Concordo Totalmente', en: 'Strongly Agree', es: 'Totalmente de acordo', fr: 'Tout à fait d\'accord', de: 'Stimme voll und ganz zu' }, value: 5 },
];

export const bigFiveConfig: TestConfig = {
  id: 'bigfive',
  title: { pt: 'Modelo Big Five (IPIP-50)', en: 'Big Five Model (IPIP-50)', es: 'Modelo Big Five', fr: 'Modèle Big Five', de: 'Big-Five-Modell' },
  subtitle: { pt: 'Arquitetura da Personalidade Humana', en: 'Human Personality Architecture', es: 'Arquitectura de la Personalidad', fr: 'Architecture de la Personnalité', de: 'Persönlichkeitsarchitektur' },
  category: { pt: 'Carreira e Liderança', en: 'Career & Leadership', es: 'Carrera', fr: 'Carrière', de: 'Karriere' },
  accentColor: 'petroleum',
  reportType: 'bigfive',
  scale: SCALE_OCEAN,
  technicalData: {
    instrument: "IPIP-NEO-50 (International Personality Item Pool)",
    citation: "Goldberg, L. R. (1992). The development of markers for the Big-Five factor structure.",
    reliabilityIndex: "Cronbach's α: 0.79 - 0.87",
    normativeData: "IPIP Global Normative Sample"
  },
  questions: [
    // ABERTURA (10)
    // Fix: Added missing es, fr, de translations for each question to satisfy LocalizedText interface
    { id: 1, dimension: 'openness', text: { pt: "Eu tenho uma imaginação vívida e ativa.", en: "I have a vivid and active imagination.", es: "I have a vivid and active imagination.", fr: "I have a vivid and active imagination.", de: "I have a vivid and active imagination." } },
    { id: 2, dimension: 'openness', text: { pt: "Eu frequentemente experimento coisas novas só para variar.", en: "I often try new things just for variety.", es: "I often try new things just for variety.", fr: "I often try new things just for variety.", de: "I often try new things just for variety." } },
    { id: 3, dimension: 'openness', text: { pt: "Eu gosto de refletir sobre ideias abstratas e filosóficas.", en: "I enjoy reflecting on abstract and philosophical ideas.", es: "I enjoy reflecting on abstract and philosophical ideas.", fr: "I enjoy reflecting on abstract and philosophical ideas.", de: "I enjoy reflecting on abstract and philosophical ideas." } },
    { id: 4, dimension: 'openness', text: { pt: "Eu aprecio diferentes formas de arte (música, pintura, literatura).", en: "I appreciate different forms of art.", es: "I appreciate different forms of art.", fr: "I appreciate different forms of art.", de: "I appreciate different forms of art." } },
    { id: 5, dimension: 'openness', text: { pt: "Eu estou sempre curioso sobre como as coisas funcionam.", en: "I am always curious about how things work.", es: "I am always curious about how things work.", fr: "I am always curious about how things work.", de: "I am always curious about how things work." } },
    { id: 6, dimension: 'openness', text: { pt: "Eu gosto de experimentar comidas, viagens e culturas diferentes.", en: "I enjoy trying different foods, travels, and cultures.", es: "I enjoy trying different foods, travels, and cultures.", fr: "I enjoy trying different foods, travels, and cultures.", de: "I enjoy trying different foods, travels, and cultures." } },
    { id: 7, dimension: 'openness', text: { pt: "Eu costumo questionar tradições e convenções sociais.", en: "I tend to question social traditions and conventions.", es: "I tend to question social traditions and conventions.", fr: "I tend to question social traditions and conventions.", de: "I tend to question social traditions and conventions." } },
    { id: 8, dimension: 'openness', text: { pt: "Eu prefiro variedade a rotina no meu dia a dia.", en: "I prefer variety over routine in my daily life.", es: "I prefer variety over routine in my daily life.", fr: "I prefer variety over routine in my daily life.", de: "I prefer variety over routine in my daily life." } },
    { id: 9, dimension: 'openness', text: { pt: "Eu me emociono facilmente com música, filmes ou histórias.", en: "I am easily moved by music, movies, or stories.", es: "I am easily moved by music, movies, or stories.", fr: "I am easily moved by music, movies, or stories.", de: "I am easily moved by music, movies, or stories." } },
    { id: 10, dimension: 'openness', text: { pt: "Eu gosto de aprender sobre tópicos complexos e desafiadores.", en: "I enjoy learning about complex and challenging topics.", es: "I enjoy learning about complex and challenging topics.", fr: "I enjoy learning about complex and challenging topics.", de: "I enjoy learning about complex and challenging topics." } },
    
    // CONSCIENCIOSIDADE (10)
    // Fix: Added missing es, fr, de translations for each question to satisfy LocalizedText interface
    { id: 11, dimension: 'conscientiousness', text: { pt: "Eu sempre completo as tarefas que começo.", en: "I always complete the tasks I start.", es: "I always complete the tasks I start.", fr: "I always complete the tasks I start.", de: "I always complete the tasks I start." } },
    { id: 12, dimension: 'conscientiousness', text: { pt: "Eu gosto de manter meu espaço de trabalho limpo e organizado.", en: "I like to keep my workspace clean and organized.", es: "I like to keep my workspace clean and organized.", fr: "I like to keep my workspace clean and organized.", de: "I like to keep my workspace clean and organized." } },
    { id: 13, dimension: 'conscientiousness', text: { pt: "Eu costumo planejar minhas atividades com antecedência.", en: "I usually plan my activities in advance.", es: "I usually plan my activities in advance.", fr: "I usually plan my activities in advance.", de: "I usually plan my activities in advance." } },
    { id: 14, dimension: 'conscientiousness', text: { pt: "Eu presto muita atenção aos detalhes no meu trabalho.", en: "I pay close attention to details in my work.", es: "I pay close attention to details in my work.", fr: "I pay close attention to details in my work.", de: "I pay close attention to details in my work." } },
    { id: 15, dimension: 'conscientiousness', text: { pt: "Eu cumpro prazos mesmo que isso exija esforço extra.", en: "I meet deadlines even if it requires extra effort.", es: "I meet deadlines even if it requires extra effort.", fr: "I meet deadlines even if it requires extra effort.", de: "I meet deadlines even if it requires extra effort." } },
    { id: 16, dimension: 'conscientiousness', text: { pt: "Eu estabeleço metas claras e trabalho para alcançá-las.", en: "I set clear goals and work to achieve them.", es: "I set clear goals and work to achieve them.", fr: "I set clear goals and work to achieve them.", de: "I set clear goals and work to achieve them." } },
    { id: 17, dimension: 'conscientiousness', text: { pt: "Eu raramente faço algo impulsivo sem pensar nas consequências.", en: "I rarely do something impulsive without thinking about consequences.", es: "I rarely do something impulsive without thinking about consequences.", fr: "I rarely do something impulsive without thinking about consequences.", de: "I rarely do something impulsive without thinking about consequences." } },
    { id: 18, dimension: 'conscientiousness', text: { pt: "Eu sigo regras e normas mesmo quando ninguém está observando.", en: "I follow rules and standards even when no one is watching.", es: "I follow rules and standards even when no one is watching.", fr: "I follow rules and standards even when no one is watching.", de: "I follow rules and standards even when no one is watching." } },
    { id: 19, dimension: 'conscientiousness', text: { pt: "Eu reviso meu trabalho várias vezes antes de enviá-lo.", en: "I review my work several times before sending it.", es: "I review my work several times before sending it.", fr: "I review my work several times before sending it.", de: "I review my work several times before sending it." } },
    { id: 20, dimension: 'conscientiousness', text: { pt: "Eu me considero uma pessoa confiável e responsável.", en: "I consider myself a reliable and responsible person.", es: "I consider myself a reliable and responsible person.", fr: "I consider myself a reliable and responsible person.", de: "I consider myself a reliable and responsible person." } },

    // EXTROVERSÃO (10)
    // Fix: Added missing es, fr, de translations for each question to satisfy LocalizedText interface
    { id: 21, dimension: 'extraversion', text: { pt: "Eu me sinto energizado depois de passar tempo com outras pessoas.", en: "I feel energized after spending time with others.", es: "I feel energized after spending time with others.", fr: "I feel energized after spending time with others.", de: "I feel energized after spending time with others." } },
    { id: 22, dimension: 'extraversion', text: { pt: "Eu gosto de ser o centro das atenções em grupos.", en: "I like to be the center of attention in groups.", es: "I like to be the center of attention in groups.", fr: "I like to be the center of attention in groups.", de: "I like to be the center of attention in groups." } },
    { id: 23, dimension: 'extraversion', text: { pt: "Eu inicio conversas facilmente com estranhos.", en: "I start conversations easily with strangers.", es: "I start conversations easily with strangers.", fr: "I start conversations easily with strangers.", de: "I start conversations easily with strangers." } },
    { id: 24, dimension: 'extraversion', text: { pt: "Eu prefiro trabalhar em equipe do que sozinho.", en: "I prefer working in a team rather than alone.", es: "I prefer working in a team rather than alone.", fr: "I prefer working in a team rather than alone.", de: "I prefer working in a team rather than alone." } },
    { id: 25, dimension: 'extraversion', text: { pt: "Eu me sinto confortável falando em público.", en: "I feel comfortable speaking in public.", es: "I feel comfortable speaking in public.", fr: "I feel comfortable speaking in public.", de: "I feel comfortable speaking in public." } },
    { id: 26, dimension: 'extraversion', text: { pt: "Eu tenho um ritmo de vida acelerado e cheio de atividades.", en: "I have a fast-paced life full of activities.", es: "I have a fast-paced life full of activities.", fr: "I have a fast-paced life full of activities.", de: "I have a fast-paced life full of activities." } },
    { id: 27, dimension: 'extraversion', text: { pt: "Eu busco situações emocionantes e estimulantes.", en: "I seek exciting and stimulating situations.", es: "I seek exciting and stimulating situations.", fr: "I seek exciting and stimulating situations.", de: "I seek exciting and stimulating situations." } },
    { id: 28, dimension: 'extraversion', text: { pt: "Eu geralmente estou de bom humor e otimista.", en: "I am usually in a good mood and optimistic.", es: "I am usually in a good mood and optimistic.", fr: "I am usually in a good mood and optimistic.", de: "I am usually in a good mood and optimistic." } },
    { id: 29, dimension: 'extraversion', text: { pt: "Eu gosto de festas e eventos sociais grandes.", en: "I enjoy parties and large social events.", es: "I enjoy parties and large social events.", fr: "I enjoy parties and large social events.", de: "I enjoy parties and large social events." } },
    { id: 30, dimension: 'extraversion', text: { pt: "Eu expresso minhas opiniões abertamente em discussões.", en: "I express my opinions openly in discussions.", es: "I express my opinions openly in discussions.", fr: "I express my opinions openly in discussions.", de: "I express my opinions openly in discussions." } },

    // AMABILIDADE (10)
    // Fix: Added missing es, fr, de translations for each question to satisfy LocalizedText interface
    { id: 31, dimension: 'agreeableness', text: { pt: "Eu geralmente confio nas intenções das pessoas.", en: "I usually trust people's intentions.", es: "I usually trust people's intentions.", fr: "I usually trust people's intentions.", de: "I usually trust people's intentions." } },
    { id: 32, dimension: 'agreeableness', text: { pt: "Eu evito conflitos e busco soluções harmoniosas.", en: "I avoid conflicts and seek harmonious solutions.", es: "I avoid conflicts and seek harmonious solutions.", fr: "I avoid conflicts and seek harmonious solutions.", de: "I avoid conflicts and seek harmonious solutions." } },
    { id: 33, dimension: 'agreeableness', text: { pt: "Eu me preocupo genuinamente com o bem-estar dos outros.", en: "I genuinely care about the well-being of others.", es: "I genuinely care about the well-being of others.", fr: "I genuinely care about the well-being of others.", de: "I genuinely care about the well-being of others." } },
    { id: 34, dimension: 'agreeableness', text: { pt: "Eu sou gentil e compassivo mesmo com pessoas difíceis.", en: "I am kind and compassionate even with difficult people.", es: "I am kind and compassionate even with difficult people.", fr: "I am kind and compassionate even with difficult people.", de: "I am kind and compassionate even with difficult people." } },
    { id: 35, dimension: 'agreeableness', text: { pt: "Eu coloco as necessidades dos outros acima das minhas frequentemente.", en: "I often put others' needs above my own.", es: "I often put others' needs above my own.", fr: "I often put others' needs above my own.", de: "I often put others' needs above my own." } },
    { id: 36, dimension: 'agreeableness', text: { pt: "Eu perdoo facilmente quando alguém me magoa.", en: "I forgive easily when someone hurts me.", es: "I forgive easily when someone hurts me.", fr: "I forgive easily when someone hurts me.", de: "I forgive easily when someone hurts me." } },
    { id: 37, dimension: 'agreeableness', text: { pt: "Eu evito criticar ou julgar as pessoas.", en: "I avoid criticizing or judging people.", es: "I avoid criticizing or judging people.", fr: "I avoid criticizing or judging people.", de: "I avoid criticizing or judging people." } },
    { id: 38, dimension: 'agreeableness', text: { pt: "Eu me sinto desconfortável em situações competitivas.", en: "I feel uncomfortable in competitive situations.", es: "I feel uncomfortable in competitive situations.", fr: "I feel uncomfortable in competitive situations.", de: "I feel uncomfortable in competitive situations." } },
    { id: 39, dimension: 'agreeableness', text: { pt: "Eu demonstro empatia facilmente pelos sentimentos alheios.", en: "I easily show empathy for others' feelings.", es: "I easily show empathy for others' feelings.", fr: "I easily show empathy for others' feelings.", de: "I easily show empathy for others' feelings." } },
    { id: 40, dimension: 'agreeableness', text: { pt: "Eu acredito que a maioria das pessoas é boa no fundo.", en: "I believe that most people are good at heart.", es: "I believe that most people are good at heart.", fr: "I believe that most people are good at heart.", de: "I believe that most people are good at heart." } },

    // ESTABILIDADE (10)
    // Fix: Added missing es, fr, de translations for each question to satisfy LocalizedText interface
    { id: 41, dimension: 'stability', text: { pt: "Eu raramente me sinto estressado ou sobrecarregado.", en: "I rarely feel stressed or overwhelmed.", es: "I rarely feel stressed or overwhelmed.", fr: "I rarely feel stressed or overwhelmed.", de: "I rarely feel stressed or overwhelmed." } },
    { id: 42, dimension: 'stability', text: { pt: "Eu lido bem com pequenas frustrações sem me irritar.", en: "I handle minor frustrations well without getting irritated.", es: "I handle minor frustrations well without getting irritated.", fr: "I handle minor frustrations well without getting irritated.", de: "I handle minor frustrations well without getting irritated." } },
    { id: 43, dimension: 'stability', text: { pt: "Meu humor é estável e previsível na maior parte do tempo.", en: "My mood is stable and predictable most of the time.", es: "My mood is stable and predictable most of the time.", fr: "My mood is stable and predictable most of the time.", de: "My mood is stable and predictable most of the time." } },
    { id: 44, dimension: 'stability', text: { pt: "Eu me sinto calmo mesmo em situações sociais desafiadoras.", en: "I feel calm even in challenging social situations.", es: "I feel calm even in challenging social situations.", fr: "I feel calm even in challenging social situations.", de: "I feel calm even in challenging social situations." } },
    { id: 45, dimension: 'stability', text: { pt: "Eu controlo meus impulsos com facilidade.", en: "I control my impulses with ease.", es: "I control my impulses with ease.", fr: "I control my impulses with ease.", de: "I control my impulses with ease." } },
    { id: 46, dimension: 'stability', text: { pt: "Eu me sinto capaz e confiante sob pressão.", en: "I feel capable and confident under pressure.", es: "I feel capable and confident under pressure.", fr: "I feel capable and confident under pressure.", de: "I feel capable and confident under pressure." } },
    { id: 47, dimension: 'stability', text: { pt: "Eu aceito críticas de forma construtiva e sem me ofender.", en: "I accept criticism constructively without being offended.", es: "I accept criticism constructively without being offended.", fr: "I accept criticism constructively without being offended.", de: "I accept criticism constructively without being offended." } },
    { id: 48, dimension: 'stability', text: { pt: "Eu raramente me sinto dominado pelas minhas emoções.", en: "I rarely feel dominated by my emotions.", es: "I rarely feel dominated by my emotions.", fr: "I rarely feel dominated by my emotions.", de: "I rarely feel dominated by my emotions." } },
    { id: 49, dimension: 'stability', text: { pt: "Eu costumo manter uma perspectiva otimista diante dos problemas.", en: "I usually maintain an optimistic perspective on problems.", es: "I usually maintain an optimistic perspective on problems.", fr: "I usually maintain an optimistic perspective on problems.", de: "I usually maintain an optimistic perspective on problems." } },
    { id: 50, dimension: 'stability', text: { pt: "Eu me recupero rápido de eventos estressantes ou negativos.", en: "I recover quickly from stressful or negative events.", es: "I recover quickly from stressful or negative events.", fr: "I recover quickly from stressful or negative events.", de: "I recover quickly from stressful or negative events." } }
  ]
};
